name: CI

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'

      - name: 'Install dependencies'
        run: pnpm install --frozen-lockfile

      - name: 'Build'
        run: pnpm run build

      - name: 'Test'
        run: pnpm run test
